# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20181124_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(null=True, upload_to=market.models.get_path)),
            ],
        ),
    ]
