# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(blank=True, to='market.FileUpload'),
        ),
    ]
