# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_post_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='files',
            new_name='otherformat',
        ),
    ]
