# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20181124_0024'),
        ('market', '0011_auto_20181124_1314'),
    ]

    operations = [
    ]
