# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_merge_20181124_1626'),
        ('market', '0012_merge_20181124_1603'),
    ]

    operations = [
    ]
