# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_merge_20181124_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
