# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-24 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20181124_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_priv',
            field=models.BooleanField(default=False),
        ),
    ]
