# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_customer_is_priv'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='books_bought',
            field=models.ManyToManyField(related_name='bought', to='market.Post'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='book',
            field=models.ManyToManyField(related_name='cart', to='market.Post'),
        ),
    ]
